"""Result, entry, and data classes for pyfs_watcher."""

from pyfs_watcher._core import (
    CopyProgress,
    DiffEntry,
    DirDiff,
    DiskUsage,
    DiskUsageEntry,
    DuplicateGroup,
    FileChange,
    HashResult,
    MovedEntry,
    RenameEntry,
    RenameFileError,
    RenameResult,
    SearchIter,
    SearchMatch,
    SearchResult,
    Snapshot,
    SnapshotEntry,
    SyncFileError,
    SyncProgress,
    SyncResult,
    VerifyChange,
    VerifyResult,
    WalkEntry,
)

__all__ = [
    "WalkEntry",
    "HashResult",
    "CopyProgress",
    "FileChange",
    "DuplicateGroup",
    "SearchMatch",
    "SearchResult",
    "SearchIter",
    "DiffEntry",
    "MovedEntry",
    "DirDiff",
    "SyncFileError",
    "SyncProgress",
    "SyncResult",
    "SnapshotEntry",
    "Snapshot",
    "VerifyChange",
    "VerifyResult",
    "DiskUsageEntry",
    "DiskUsage",
    "RenameEntry",
    "RenameFileError",
    "RenameResult",
]
